// Map English MangaDex genres -> Arabic labels
export const GENRE_AR = {
  "Action": "أكشن",
  "Adventure": "مغامرة",
  "Comedy": "كوميديا",
  "Drama": "دراما",
  "Fantasy": "فانتازيا",
  "Horror": "رعب",
  "Magic": "سحر",
  "Mystery": "غموض",
  "Romance": "رومانسي",
  "Sci-Fi": "خيال علمي",
  "Slice of Life": "شريحة حياة",
  "Sports": "رياضي",
  "Supernatural": "خارق للطبيعة",
  "Thriller": "إثارة",
  "Psychological": "نفسي",
  "Historical": "تاريخي",
  "School Life": "حياة مدرسية",
  "Isekai": "عالم آخر",
  "Reincarnation": "تناسخ",
  "Harem": "حريم",
  "Martial Arts": "فنون قتالية",
  "Monsters": "وحوش",
  "Demons": "شياطين",
  "Survival": "نجاة",
  "Time Travel": "سفر عبر الزمن",
  "Villainess": "شريرة",
  "Video Games": "ألعاب فيديو",
  "Gore": "دموي",
  "Girls' Love": "Girls' Love",
  "Boys' Love": "Boys' Love",
  "Office Workers": "موظفون",
  "Animals": "حيوانات",
  "Award Winning": "حائز على جوائز",
  "Monster Girls": "فتيات الوحوش",
  "Military": "عسكري",
  "Long Strip": "ويب تون",
  "Web Comic": "ويب كوميك",
  "Full Color": "ملوّن",
  "Adaptation": "اقتباس",
  "Gyaru": "جاياروا",
};

export const arGenre = (g) => GENRE_AR[g] || g;
